**Realizando novas predições com o nosso modelo serializado**
-

Essa é a maneira mais manual de realizar novas predições, porém não é a mais segura, pois dependemos do código para salvar o modelo, importar o modelo, importar os dados etc.

Isso significa que uma série de regras e caminhos precisam estar perfeitamente alinhados para a minha predição funcionar.

In [10]:
import pandas as pd

model_series = pd.read_pickle("model.pkl") #Leio o modelo
model = model_series['Model'] #Separo o modelo e as features em duas variáveis separadas
features = model_series['Features']

In [5]:
df = pd.read_csv("data/abt_churn.csv") #Lendo os dados da abt
df.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn
0,2024-06-01,000ff655-fa9f-4baa-a108-47f581ec52a1,266,27,9.851852,635,2635,-2000,1.0,89.0,...,151,151,0,3.889781,3.278281,2.135602,1.516314,4.101926,8.944444,1
1,2024-10-01,000ff655-fa9f-4baa-a108-47f581ec52a1,268,28,9.571429,686,2686,-2000,4.0,211.0,...,51,51,0,3.309865,2.567615,2.328737,1.288278,2.920954,5.167037,1
2,2024-04-01,000ff655-fa9f-4baa-a108-47f581ec52a1,188,11,17.090909,275,1275,-1000,3.0,28.0,...,275,1275,-1000,3.805468,1.820201,3.739048,0.798622,2.634551,7.162791,0
3,2024-05-01,000ff655-fa9f-4baa-a108-47f581ec52a1,262,24,10.916667,484,2484,-2000,2.0,58.0,...,107,1107,-1000,4.246216,3.255244,2.322640,1.275749,4.275765,9.922414,0
4,2024-08-01,001749bd-37b5-4b1e-8111-f9fbba90f530,1,1,1.000000,50,50,0,21.0,21.0,...,50,50,0,0.013317,0.103973,0.236635,0.104533,0.063302,0.000000,1

In [16]:
amostra = df[df['dtRef'] == df['dtRef'].max()].sample(3) #Criando amostra com as três observações mais recentes
amostra = amostra.drop('flagChurn', axis=1)
amostra.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdeDiasD28,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg
4201,2025-04-01,bbaf6627-0198-48bc-b48f-accc0e6ef70a,4,1,4.000000,4,4,0,22.0,22.0,...,1,4,4,0,0.049110,0.084922,1.011651,0.007724,0.004242,0.000000
3943,2025-04-01,af4c1efa-6ca0-4dd8-aa84-9751c2805d4b,263,107,2.457944,4385,7385,-3000,4.0,273.0,...,12,703,703,0,3.228977,9.086702,0.621645,8.467313,7.831990,7.057929
4011,2025-04-01,b2f9d026-0727-4125-b84b-c60af3148a15,635,78,8.141026,5351,6351,-1000,11.0,428.0,...,1,1,1,0,7.796198,6.623951,2.058969,10.332633,6.735405,2.352643

In [13]:
predict = model.predict_proba(amostra[features])[:,1]
predict

array([0.43893454, 0.75588555, 0.24204736])

In [15]:
amostra['proba'] = predict #Colocando a predição numa coluna nova do dataframe
amostra.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn,proba
2944,2025-04-01,7e144941-c3a5-4efc-b842-aae28cc08ef2,8,5,1.60,253,253,0,4.0,70.0,...,101,0,0.098220,0.424612,0.404660,0.488536,0.268313,0.0,0,0.438935
5481,2025-04-01,fe9f68ac-b0fe-4a1a-b9f7-6a4300d47963,4,1,4.00,53,53,0,15.0,15.0,...,53,0,0.049110,0.084922,1.011651,0.102342,0.056208,0.0,1,0.755886
850,2025-04-01,1d15e956-6689-4ac0-b331-f81706815411,27,20,1.35,1007,1007,0,1.0,64.0,...,152,0,0.331492,1.698449,0.341432,1.944489,1.067950,0.0,0,0.242047