**Importando modelo registrado no MLFLow**
-

Essa é a versão mais segura e robusta de usar os nossos modelos treinados, pois deixa a cargo do mlflow gerenciar o modelo e armazenar as informações e versões dele.

In [45]:
import mlflow
import pandas as pd

In [46]:
mlflow.set_tracking_uri('http://localhost:5000')

model = mlflow.sklearn.load_model('models:/model_churn/1') #Passo o caminho do modelo, junto da versão do modelo que queremos importar. Como criamos só a primeira versão do modelo, passamos somente o número 1 no caminho

In [47]:
dir(model) #Procurando o

['__abstractmethods__',
 '__annotate_func__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_is_fitted__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_can_fit_transform',
 '_can_inverse_transform',
 '_can_transform',
 '_check_estimators_are_instances',
 '_check_method_params',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_final_estimator',
 '_fit',
 '_get_class_level_metadata_request_values',
 '_get_doc_link',
 '_get_fitted_attr_html',
 '_get_metadata_for_step',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params',
 '_get_params_html',
 '_html_repr',
 '_init_callback_context',
 '_iter',
 '_log_message',
 '_parameter_constraints',
 '_replace_estimator',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_params',
 '_sk_visual_block_',
 '_validate_names',
 '_validate_params',
 '_validate_steps',
 'classes_',
 'feature_names_in_',
 'fit',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'memory',
 'n_features_in_',
 'named_steps',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'score',
 'set_callbacks',
 'set_output',
 'set_params',
 'set_score_request',
 'steps',
 'transform_input',
 'verbose']

In [48]:
features = model.feature_names_in_
features

['qtdeDiasD14',
 'propAvgQtdeDias',
 'qtdeDiasPrimeiraTransacao',
 'qtdeDiasUltimaTransacao',
 'propAvgQtdePontosPos',
 'propAvgSaldoPontos',
 'propAvgQtdeTransacoes',
 'propAvgMediaTransacoesDias',
 'qtdeTransacoesD28',
 'qtdePontosPos',
 'qtdeDiasD28',
 'qtdeTransacoesD7',
 'qtdeChatMessage',
 'mediaTransacoesDias',
 'qtdeTransacoes',
 'qtdePontosPosD7',
 'saldoPontosD28',
 'qtdePontosPosD28',
 'qtdeDias',
 'saldoPontos',
 'qtdeTransacoesD14',
 'saldoPontosD14',
 'qtdePontosPosD14',
 'qtdePresença',
 'qtdSkuDistintos']

In [49]:
model

Pipeline(steps=[('Discretizar',
                 DecisionTreeDiscretiser(bin_output='bin_number',
                                         regression=False,
                                         variables=['qtdeDiasD14',
                                                    'propAvgQtdeDias',
                                                    'qtdeDiasPrimeiraTransacao',
                                                    'qtdeDiasUltimaTransacao',
                                                    'propAvgQtdePontosPos',
                                                    'propAvgSaldoPontos',
                                                    'propAvgQtdeTransacoes',
                                                    'propAvgMediaTransacoesDias',
                                                    'qtdeTransacoesD28',
                                                    'qtdePontosPos',
                                                    'qtdeDiasD28',
                                                    'qtdeTrans...
                                          'qtdeDias', 'saldoPontos',
                                          'qtdeTransacoesD14', 'saldoPontosD14',
                                          'qtdePontosPosD14', 'qtdePresença',
                                          'qtdSkuDistintos'])),
                ('Grid',
                 GridSearchCV(cv=3,
                              estimator=RandomForestClassifier(n_jobs=-1,
                                                               random_state=42),
                              param_grid={'criterion': ['entropy', 'log_loss',
                                                        'gini'],
                                          'min_samples_leaf': [15, 20, 25, 30,
                                                               50],
                                          'n_estimators': [100, 200, 500,
                                                           1000]},
                              scoring='roc_auc', verbose=4))])

In [50]:
df = pd.read_csv("data/abt_churn.csv") #Lendo os dados da abt
df.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn
0,2024-06-01,000ff655-fa9f-4baa-a108-47f581ec52a1,266,27,9.851852,635,2635,-2000,1.0,89.0,...,151,151,0,3.889781,3.278281,2.135602,1.516314,4.101926,8.944444,1
1,2024-10-01,000ff655-fa9f-4baa-a108-47f581ec52a1,268,28,9.571429,686,2686,-2000,4.0,211.0,...,51,51,0,3.309865,2.567615,2.328737,1.288278,2.920954,5.167037,1
2,2024-04-01,000ff655-fa9f-4baa-a108-47f581ec52a1,188,11,17.090909,275,1275,-1000,3.0,28.0,...,275,1275,-1000,3.805468,1.820201,3.739048,0.798622,2.634551,7.162791,0
3,2024-05-01,000ff655-fa9f-4baa-a108-47f581ec52a1,262,24,10.916667,484,2484,-2000,2.0,58.0,...,107,1107,-1000,4.246216,3.255244,2.322640,1.275749,4.275765,9.922414,0
4,2024-08-01,001749bd-37b5-4b1e-8111-f9fbba90f530,1,1,1.000000,50,50,0,21.0,21.0,...,50,50,0,0.013317,0.103973,0.236635,0.104533,0.063302,0.000000,1

In [51]:
amostra = df[df['dtRef'] == df['dtRef'].max()].sample(3) #Criando amostra com as três observações mais recentes
amostra = amostra.drop('flagChurn', axis=1)
amostra.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdeDiasD28,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg
311,2025-04-01,0ade65a7-c1b0-4aa5-8ab6-a4ad78028037,1516,204,7.431373,2458,24508,-22050,4.0,354.0,...,14,732,732,0,18.612656,17.324180,1.879489,4.746330,25.991388,51.875775
2718,2025-04-01,748bb5c7-44c5-4841-b10a-6593a1b6208c,48,14,3.428571,734,734,0,1.0,88.0,...,5,254,254,0,0.589319,1.188914,0.867129,1.417334,0.778427,0.000000
2187,2025-04-01,5b7a7182-854c-42f3-b459-752bd3e4f0bf,210,36,5.833333,1345,6595,-5250,20.0,288.0,...,1,1,1,0,2.578270,3.057208,1.475324,2.597158,6.994173,12.351375

In [52]:
predict = model.predict_proba(amostra[features])[:,1]
predict

array([0.01056281, 0.14107043, 0.63490905])

In [53]:
amostra['proba'] = predict #Colocando a predição numa coluna nova do dataframe
amostra.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,proba
311,2025-04-01,0ade65a7-c1b0-4aa5-8ab6-a4ad78028037,1516,204,7.431373,2458,24508,-22050,4.0,354.0,...,732,732,0,18.612656,17.324180,1.879489,4.746330,25.991388,51.875775,0.010563
2718,2025-04-01,748bb5c7-44c5-4841-b10a-6593a1b6208c,48,14,3.428571,734,734,0,1.0,88.0,...,254,254,0,0.589319,1.188914,0.867129,1.417334,0.778427,0.000000,0.141070
2187,2025-04-01,5b7a7182-854c-42f3-b459-752bd3e4f0bf,210,36,5.833333,1345,6595,-5250,20.0,288.0,...,1,1,0,2.578270,3.057208,1.475324,2.597158,6.994173,12.351375,0.634909

Ele facilita também para trocarmos o modelo que está em produção, já que podemos simplesmente mudar a versão do modelo.

Vamos trocar o modelo para o que tem melhor AUC

In [54]:
model = mlflow.sklearn.load_model('models:/model_churn/2') #Mudamos a versão do modelo model_churn para 2

predict = model.predict_proba(amostra[features])[:,1]
amostra['proba_modelv2'] = predict
amostra

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,proba,proba_modelv2
311,2025-04-01,0ade65a7-c1b0-4aa5-8ab6-a4ad78028037,1516,204,7.431373,2458,24508,-22050,4.0,354.0,...,732,0,18.612656,17.324180,1.879489,4.746330,25.991388,51.875775,0.010563,0.006165
2718,2025-04-01,748bb5c7-44c5-4841-b10a-6593a1b6208c,48,14,3.428571,734,734,0,1.0,88.0,...,254,0,0.589319,1.188914,0.867129,1.417334,0.778427,0.000000,0.141070,0.185079
2187,2025-04-01,5b7a7182-854c-42f3-b459-752bd3e4f0bf,210,36,5.833333,1345,6595,-5250,20.0,288.0,...,1,0,2.578270,3.057208,1.475324,2.597158,6.994173,12.351375,0.634909,0.609074

Para melhorarmos MAIS ainda, podemos criar o código para que ele sempre use o último modelo registrado no mlflow, tirando a necessidade de alterar o caminho sempre que trocarmos o modelo em produção

In [55]:
models = mlflow.search_registered_models(filter_string="name= 'model_churn'") #Procurando as informações dos modelos registrados, e filtrando o nome (nesse caso model_churn)

models[0] #Modelo registrado no mlflow. Nele temos as informações do nosso modelo num objeto/instância

<RegisteredModel: aliases={}, creation_timestamp=1782661057670, deployment_job_id='', deployment_job_state='DEPLOYMENT_JOB_CONNECTION_STATE_UNSPECIFIED', description='', last_updated_timestamp=1782662598507, latest_versions=[<ModelVersion: aliases=[], creation_timestamp=1782662598507, current_stage='None', deployment_job_state=<ModelVersionDeploymentJobState: current_task_name='', job_id='', job_state='DEPLOYMENT_JOB_CONNECTION_STATE_UNSPECIFIED', run_id='', run_state='DEPLOYMENT_JOB_RUN_STATE_UNSPECIFIED'>, description='', last_updated_timestamp=1782662598507, metrics=None, model_id=None, name='model_churn', params=None, run_id='1b57a89325d845648aa1f6fe14c458ca', run_link='', source='models:/m-712aa742b8bd4c92b684e717d533edc0', status='READY', status_message=None, tags={}, user_id='', version='2', workspace='default'>], name='model_churn', tags={}, workspace='default'>

In [56]:
models[0].latest_versions

[<ModelVersion: aliases=[], creation_timestamp=1782662598507, current_stage='None', deployment_job_state=<ModelVersionDeploymentJobState: current_task_name='', job_id='', job_state='DEPLOYMENT_JOB_CONNECTION_STATE_UNSPECIFIED', run_id='', run_state='DEPLOYMENT_JOB_RUN_STATE_UNSPECIFIED'>, description='', last_updated_timestamp=1782662598507, metrics=None, model_id=None, name='model_churn', params=None, run_id='1b57a89325d845648aa1f6fe14c458ca', run_link='', source='models:/m-712aa742b8bd4c92b684e717d533edc0', status='READY', status_message=None, tags={}, user_id='', version='2', workspace='default'>]

In [57]:
latest_version = max([i.version for i in models[0].latest_versions]) #Percorro dentro das versões do objeto ModelVersion por meio de um loop for, armazeno as versões dentro de i.version e uso o max para pegar a maior versão (Ou a última, já que as versões são criadas de maneira crescente).
latest_version

'2'

In [58]:
model = mlflow.sklearn.load_model(f'models:/model_churn/{latest_version}') #formatamos a última versão do modelo dentro do caminho, para que o script sempre use a versão mais recente do modelo

predict = model.predict_proba(amostra[features])[:,1]
amostra['proba_latestmodel'] = predict
amostra

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,proba,proba_modelv2,proba_latestmodel
311,2025-04-01,0ade65a7-c1b0-4aa5-8ab6-a4ad78028037,1516,204,7.431373,2458,24508,-22050,4.0,354.0,...,0,18.612656,17.324180,1.879489,4.746330,25.991388,51.875775,0.010563,0.006165,0.006165
2718,2025-04-01,748bb5c7-44c5-4841-b10a-6593a1b6208c,48,14,3.428571,734,734,0,1.0,88.0,...,0,0.589319,1.188914,0.867129,1.417334,0.778427,0.000000,0.141070,0.185079,0.185079
2187,2025-04-01,5b7a7182-854c-42f3-b459-752bd3e4f0bf,210,36,5.833333,1345,6595,-5250,20.0,288.0,...,0,2.578270,3.057208,1.475324,2.597158,6.994173,12.351375,0.634909,0.609074,0.609074